ALTER TABLE players ADD COLUMN IF NOT EXISTS current_town TEXT NOT NULL DEFAULT 'dawnmark';
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_encounter_id TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN IF NOT EXISTS encounter_day INTEGER NOT NULL DEFAULT 0;
