ALTER TABLE players
  ADD COLUMN IF NOT EXISTS rep_knights      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rep_guild        INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rep_druids       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rep_necromancers INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rep_merchants    INTEGER NOT NULL DEFAULT 0;
